import type { Handoff, Listing, Match, TimeSlot, University, User, UserNotification, Want } from "./types";

export const university: University = {
  id: "uw",
  name: "University of Waterloo",
  shortName: "UWaterloo",
  emailDomain: "uwaterloo.ca",
};

export const users: User[] = [
  {
    id: "u-marcus",
    name: "Marcus Chen",
    email: "m8chen@uwaterloo.ca",
    universityId: "uw",
    home: "Moving in from Vancouver",
    destination: "Phillip St",
    moveStatus: "arriving",
    moveDate: "2026-09-15T18:05:00-04:00",
    note: "2B Software Engineering",
  },
  {
    id: "u-priya",
    name: "Priya Raman",
    email: "p3raman@uwaterloo.ca",
    universityId: "uw",
    home: "318 St. Jerome's",
    destination: null,
    moveStatus: "leaving",
    moveDate: "2026-09-15T23:05:00-04:00",
    note: "Co-op term in Toronto",
  },
  {
    id: "u-sofia",
    name: "Sofia Martins",
    email: "s7martins@uwaterloo.ca",
    universityId: "uw",
    home: "Moving in from Mississauga",
    destination: "Village 1",
    moveStatus: "arriving",
    moveDate: "2026-09-14T23:05:00-04:00",
    note: "1A Biomedical Engineering",
  },
  {
    id: "u-aisha",
    name: "Aisha Bello",
    email: "a2bello@uwaterloo.ca",
    universityId: "uw",
    home: "Village 1",
    destination: null,
    moveStatus: "leaving",
    moveDate: "2026-09-15T05:05:00-04:00",
    note: "Co-op term in Ottawa",
  },
  {
    id: "u-daniel",
    name: "Daniel Osei",
    email: "d4osei@uwaterloo.ca",
    universityId: "uw",
    home: "Village 1",
    destination: null,
    moveStatus: "leaving",
    moveDate: "2026-09-14T19:05:00-04:00",
    note: "Co-op term in Calgary",
  },
  {
    id: "u-hana",
    name: "Hana Yoshida",
    email: "h6yoshida@uwaterloo.ca",
    universityId: "uw",
    home: "Mackenzie King Village",
    destination: null,
    moveStatus: "leaving",
    moveDate: "2026-09-18T05:05:00-04:00",
    note: "Co-op term in San Francisco",
  },
  {
    id: "u-jordan",
    name: "Jordan Kim",
    email: "j5kim@uwaterloo.ca",
    universityId: "uw",
    home: "Columbia St W",
    destination: null,
    moveStatus: "staying",
    moveDate: null,
    note: "4A Mechatronics",
  },
  {
    id: "u-owen",
    name: "Owen Brooks",
    email: "o9brooks@uwaterloo.ca",
    universityId: "uw",
    home: "King St N",
    destination: null,
    moveStatus: "staying",
    moveDate: null,
    note: "3A Architecture",
  },
];

type ListingSeed = Omit<Listing, "universityId" | "isBundle" | "parentId" | "status" | "createdAt" | "description"> &
  Partial<Pick<Listing, "isBundle" | "parentId" | "status" | "createdAt" | "description">>;

function listing(seed: ListingSeed): Listing {
  return {
    universityId: "uw",
    description: "",
    isBundle: false,
    parentId: null,
    status: "available",
    createdAt: "2026-09-10T21:05:00-04:00",
    ...seed,
  };
}

const inPriyasRoom = {
  sellerId: "u-priya",
  category: "furniture",
  offerType: "sale",
  pickupArea: "St. Jerome's",
  expiresAt: "2026-09-15T21:05:00-04:00",
  parentId: "l-priya-room",
} as const;

export const listings: Listing[] = [
  listing({
    id: "l-mattress",
    sellerId: "u-daniel",
    title: "Twin mattress and bed frame",
    description:
      "Frame comes apart with an Allen key, which I’ll leave taped to it. Mattress has a protector on it the whole time. Free, it just can’t come to Calgary.",
    kind: "Bed",
    category: "furniture",
    offerType: "free",
    priceCents: null,
    condition: "good",
    pickupArea: "Village 1",
    expiresAt: "2026-09-14T00:05:00-04:00",
    createdAt: "2026-09-13T06:35:00-04:00",
  }),
  listing({
    id: "l-lab-coat",
    sellerId: "u-aisha",
    title: "Lab coat and safety goggles",
    description:
      "Size M lab coat from CHEM 120 labs, washed and folded. The goggles have no scratches. I leave for Ottawa tomorrow, so these need to go tonight.",
    kind: "Coat",
    category: "school",
    offerType: "sale",
    priceCents: 1500,
    condition: "good",
    pickupArea: "Village 1",
    expiresAt: "2026-09-14T03:05:00-04:00",
    createdAt: "2026-09-12T18:35:00-04:00",
  }),
  listing({
    id: "l-floor-lamp",
    sellerId: "u-daniel",
    title: "Tall floor lamp",
    description: "IKEA floor lamp, bulb included. It’ll be on the porch. Just take it before I lock up.",
    kind: "Lamp",
    category: "furniture",
    offerType: "free",
    priceCents: null,
    condition: "good",
    pickupArea: "Village 1",
    expiresAt: "2026-09-14T05:05:00-04:00",
    createdAt: "2026-09-13T03:05:00-04:00",
  }),
  listing({
    id: "l-bookshelf",
    sellerId: "u-daniel",
    title: "5-shelf bookcase",
    description:
      "A little wobbly but it holds a full shelf of textbooks without complaint. I can help carry it down the stairs.",
    kind: "Shelf",
    category: "furniture",
    offerType: "free",
    priceCents: null,
    condition: "fair",
    pickupArea: "Village 1",
    expiresAt: "2026-09-14T18:05:00-04:00",
    createdAt: "2026-09-12T05:20:00-04:00",
  }),
  listing({
    id: "l-calculator",
    sellerId: "u-aisha",
    title: "TI-84 Plus CE graphing calculator",
    description:
      "Bought it for MATH 137 and barely used it after midterms. Comes with the charging cable and the slide case.",
    kind: "TI-84",
    category: "school",
    offerType: "sale",
    priceCents: 6000,
    condition: "like-new",
    pickupArea: "Village 1",
    expiresAt: "2026-09-15T01:05:00-04:00",
    createdAt: "2026-09-11T19:05:00-04:00",
  }),
  listing({
    id: "l-priya-room",
    sellerId: "u-priya",
    title: "Everything from my room on Lester",
    description:
      "I’m off to Toronto for co-op, so the whole room setup has to go. Good fit for a Lester or Sunview unit. You get all eight things in one pickup, and I’ll help load the car.",
    kind: "Room",
    category: "furniture",
    offerType: "sale",
    priceCents: 14000,
    condition: "good",
    pickupArea: "St. Jerome's",
    expiresAt: "2026-09-15T21:05:00-04:00",
    isBundle: true,
    createdAt: "2026-09-13T17:50:00-04:00",
  }),
  listing({ ...inPriyasRoom, id: "l-priya-desk", title: "IKEA Micke desk, white", kind: "Desk", priceCents: 4500, condition: "good" }),
  listing({ ...inPriyasRoom, id: "l-priya-chair", title: "Mesh desk chair", kind: "Chair", priceCents: 3000, condition: "good" }),
  listing({ ...inPriyasRoom, id: "l-priya-lamp", title: "Desk lamp with USB port", kind: "Lamp", priceCents: 1500, condition: "like-new" }),
  listing({ ...inPriyasRoom, id: "l-priya-fridge", title: "Danby mini fridge, 3.1 cu ft", kind: "Fridge", priceCents: 6000, condition: "good" }),
  listing({ ...inPriyasRoom, id: "l-priya-shelf", title: "3-shelf bookcase", kind: "Shelf", priceCents: 2000, condition: "good" }),
  listing({ ...inPriyasRoom, id: "l-priya-topper", title: "Twin XL mattress topper", kind: "Bed", priceCents: 1500, condition: "fair" }),
  listing({ ...inPriyasRoom, id: "l-priya-mirror", title: "Full-length mirror", kind: "Mirror", priceCents: 1500, condition: "good" }),
  listing({ ...inPriyasRoom, id: "l-priya-hamper", title: "Laundry hamper", kind: "Hamper", priceCents: 500, condition: "good" }),
  listing({
    id: "l-poang",
    sellerId: "u-hana",
    title: "IKEA Poäng armchair",
    description:
      "Birch frame with a beige cushion. Great reading chair. The cushion cover comes off and goes in the wash.",
    kind: "Chair",
    category: "furniture",
    offerType: "sale",
    priceCents: 3500,
    condition: "good",
    pickupArea: "Mackenzie King Village",
    expiresAt: "2026-09-16T19:05:00-04:00",
    createdAt: "2026-09-13T00:05:00-04:00",
  }),
  listing({
    id: "l-biology",
    sellerId: "u-hana",
    title: "Campbell Biology, 12th edition",
    description: "Some highlighting in the first ten chapters. Used it for BIOL 130.",
    kind: "Book",
    category: "school",
    offerType: "sale",
    priceCents: 4000,
    condition: "good",
    pickupArea: "Mackenzie King Village",
    expiresAt: "2026-09-16T19:05:00-04:00",
    createdAt: "2026-09-13T00:15:00-04:00",
  }),
  listing({
    id: "l-desk-converter",
    sellerId: "u-hana",
    title: "Standing desk converter",
    description: "Sits on top of any desk and raises up to 16 inches. Fits a laptop and one monitor side by side.",
    kind: "Desk",
    category: "furniture",
    offerType: "sale",
    priceCents: 5000,
    condition: "like-new",
    pickupArea: "Mackenzie King Village",
    expiresAt: "2026-09-18T03:05:00-04:00",
    createdAt: "2026-09-13T00:25:00-04:00",
  }),
  listing({
    id: "l-mini-fridge",
    sellerId: "u-owen",
    title: "Mini fridge, 1.7 cu ft",
    description: "Quiet enough for a bedroom. Rent it for the term and bring it back at the end of December.",
    kind: "Fridge",
    category: "furniture",
    offerType: "rent",
    priceCents: 2500,
    condition: "good",
    pickupArea: "King St N",
    expiresAt: null,
    createdAt: "2026-09-13T18:05:00-04:00",
  }),
  listing({
    id: "l-monitor",
    sellerId: "u-jordan",
    title: "Dell 27 inch monitor",
    description:
      "1440p with HDMI and DisplayPort. I have two and only use one, so rent it for the term and bring it back in December.",
    kind: "Screen",
    category: "school",
    offerType: "rent",
    priceCents: 3000,
    condition: "good",
    pickupArea: "Columbia St W",
    expiresAt: null,
    createdAt: "2026-09-13T06:05:00-04:00",
  }),
  listing({
    id: "l-futon",
    sellerId: "u-owen",
    title: "Futon that folds into a bed",
    description: "Still folds flat without a fight. It won’t fit in a sedan, so bring a friend and walk it over.",
    kind: "Futon",
    category: "furniture",
    offerType: "sale",
    priceCents: 8000,
    condition: "fair",
    pickupArea: "King St N",
    expiresAt: null,
    createdAt: "2026-09-12T20:05:00-04:00",
  }),
  listing({
    id: "l-rolling-cart",
    sellerId: "u-owen",
    title: "3-tier rolling cart",
    description: "Good for a desk-side printer or bathroom stuff. Free to whoever wants it.",
    kind: "Cart",
    category: "furniture",
    offerType: "free",
    priceCents: null,
    condition: "good",
    pickupArea: "King St N",
    expiresAt: null,
    createdAt: "2026-09-12T17:05:00-04:00",
  }),
  listing({
    id: "l-office-chair",
    sellerId: "u-jordan",
    title: "Office chair with armrests",
    description: "Adjustable height and armrests. Replaced it with a new one, nothing wrong with it.",
    kind: "Chair",
    category: "furniture",
    offerType: "sale",
    priceCents: 4500,
    condition: "good",
    pickupArea: "Columbia St W",
    expiresAt: null,
    createdAt: "2026-09-12T02:35:00-04:00",
  }),
  listing({
    id: "l-drafting-kit",
    sellerId: "u-owen",
    title: "Drafting kit for ARCH 172",
    description: "Scale ruler, set squares, compass and lead holder. Only the eraser is used up.",
    kind: "Kit",
    category: "school",
    offerType: "sale",
    priceCents: 1500,
    condition: "like-new",
    pickupArea: "King St N",
    expiresAt: null,
    createdAt: "2026-09-11T01:05:00-04:00",
  }),
  listing({
    id: "l-kitchen-table",
    sellerId: "u-jordan",
    title: "Kitchen table with two chairs",
    description: "Solid wood, some scratches on top. Needs a car or two people to carry.",
    kind: "Table",
    category: "furniture",
    offerType: "sale",
    priceCents: 6000,
    condition: "fair",
    pickupArea: "Columbia St W",
    expiresAt: null,
    createdAt: "2026-09-08T22:05:00-04:00",
  }),
  listing({
    id: "l-whiteboard",
    sellerId: "u-jordan",
    title: "Whiteboard, 36 by 24 inches",
    description: "Magnetic, with three markers and an eraser. Very good for working through problem sets.",
    kind: "Board",
    category: "school",
    offerType: "sale",
    priceCents: 2000,
    condition: "good",
    pickupArea: "Columbia St W",
    expiresAt: null,
    status: "claimed",
    createdAt: "2026-09-10T04:05:00-04:00",
  }),
  listing({
    id: "l-bedside-table",
    sellerId: "u-priya",
    title: "Bedside table with a drawer",
    description: "Small white nightstand.",
    kind: "Table",
    category: "furniture",
    offerType: "sale",
    priceCents: 1000,
    condition: "good",
    pickupArea: "St. Jerome's",
    expiresAt: "2026-09-15T21:05:00-04:00",
    status: "claimed",
    createdAt: "2026-09-11T17:05:00-04:00",
  }),

  // A spread across every category and all four offer types. Renting and
  // lending only come from students who are staying (Jordan, Owen); anyone
  // leaving sells or gives away, with a deadline before they go.

  // Furniture
  listing({
    id: "l-bean-bag",
    sellerId: "u-daniel",
    title: "Bean bag chair",
    description: "The big squishy kind. A bit flattened but still comfy for gaming or reading. Free, it won’t fit in my suitcase.",
    kind: "Chair",
    category: "furniture",
    offerType: "free",
    priceCents: null,
    condition: "fair",
    pickupArea: "Village 1",
    expiresAt: "2026-09-13T23:15:00-04:00",
    createdAt: "2026-09-13T04:05:00-04:00",
    photoUrl: "/photos/bean-bag-chair.webp",
  }),
  listing({
    id: "l-folding-table",
    sellerId: "u-jordan",
    title: "Folding table and four chairs",
    description: "For a study group, a board game night or a birthday. Folds flat into a hatchback. Bring it back within the week.",
    kind: "Table",
    category: "furniture",
    offerType: "lend",
    priceCents: null,
    condition: "good",
    pickupArea: "Columbia St W",
    expiresAt: null,
    createdAt: "2026-09-11T03:35:00-04:00",
    photoUrl: "/photos/folding-table.webp",
  }),
  listing({
    id: "l-shoe-rack",
    sellerId: "u-hana",
    title: "Bamboo shoe rack, 3 tiers",
    description: "Holds about nine pairs. Fits right behind a residence door.",
    kind: "Rack",
    category: "furniture",
    offerType: "sale",
    priceCents: 800,
    condition: "good",
    pickupArea: "Mackenzie King Village",
    expiresAt: "2026-09-13T23:10:00-04:00",
    createdAt: "2026-09-13T00:35:00-04:00",
    photoUrl: "/photos/shoe-rack.webp",
  }),

  // School materials
  listing({
    id: "l-physics-textbook",
    sellerId: "u-priya",
    title: "University Physics, 15th edition",
    description: "Young and Freedman, the PHYS 121 textbook. A few pencil notes in the margins. Access code already used.",
    kind: "Book",
    category: "school",
    offerType: "sale",
    priceCents: 3500,
    condition: "good",
    pickupArea: "St. Jerome's",
    expiresAt: "2026-09-13T20:25:00-04:00",
    createdAt: "2026-09-12T19:05:00-04:00",
    photoUrl: "/photos/physics-textbook.webp",
  }),
  listing({
    id: "l-exam-calculator",
    sellerId: "u-jordan",
    title: "Casio fx-991MS exam calculator",
    description: "The one that’s allowed in engineering exams. Borrow it for midterms if yours died, just bring it back after.",
    kind: "Calculator",
    category: "school",
    offerType: "lend",
    priceCents: null,
    condition: "good",
    pickupArea: "Columbia St W",
    expiresAt: null,
    createdAt: "2026-09-11T21:05:00-04:00",
    photoUrl: "/photos/exam-calculator.webp",
  }),
  listing({
    id: "l-binders",
    sellerId: "u-hana",
    title: "Binders, dividers and notebooks",
    description: "Four 1-inch binders, a pack of dividers and six lined notebooks I never opened. Take all of it.",
    kind: "Stationery",
    category: "school",
    offerType: "free",
    priceCents: null,
    condition: "like-new",
    pickupArea: "Mackenzie King Village",
    expiresAt: "2026-09-17T21:05:00-04:00",
    createdAt: "2026-09-13T00:45:00-04:00",
    photoUrl: "/photos/binders.webp",
  }),

  // Kitchen
  listing({
    id: "l-rice-cooker",
    sellerId: "u-daniel",
    title: "Rice cooker, 6 cup",
    description: "Aroma rice cooker with the steamer tray and measuring cup. Inner pot has no scratches.",
    kind: "Cooker",
    category: "kitchen",
    offerType: "sale",
    priceCents: 1500,
    condition: "good",
    pickupArea: "Village 1",
    expiresAt: "2026-09-13T20:20:00-04:00",
    createdAt: "2026-09-13T04:15:00-04:00",
    photoUrl: "/photos/rice-cooker.webp",
  }),
  listing({
    id: "l-instant-pot",
    sellerId: "u-owen",
    title: "Instant Pot, 6 quart",
    description: "Pressure cooker, slow cooker and rice cooker in one. Rent it for the term and bring it back in December.",
    kind: "Cooker",
    category: "kitchen",
    offerType: "rent",
    priceCents: 2000,
    condition: "like-new",
    pickupArea: "King St N",
    expiresAt: null,
    createdAt: "2026-09-11T23:05:00-04:00",
    photoUrl: "/photos/instant-pot.webp",
  }),
  listing({
    id: "l-pots-pans",
    sellerId: "u-aisha",
    title: "Pots, pans and cooking utensils",
    description: "Two pots, a frying pan, a spatula, a ladle and a colander. Everything a first kitchen needs. Gone when I leave tomorrow.",
    kind: "Cookware",
    category: "kitchen",
    offerType: "free",
    priceCents: null,
    condition: "fair",
    pickupArea: "Village 1",
    expiresAt: "2026-09-13T23:20:00-04:00",
    createdAt: "2026-09-13T05:05:00-04:00",
    photoUrl: "/photos/pots-pans.webp",
  }),

  // Electronics
  listing({
    id: "l-keyboard-mouse",
    sellerId: "u-hana",
    title: "Logitech wireless keyboard and mouse",
    description: "Shares one USB receiver. Batteries included. Moving to San Francisco and bringing my laptop only.",
    kind: "Keyboard",
    category: "electronics",
    offerType: "sale",
    priceCents: 2000,
    condition: "like-new",
    pickupArea: "Mackenzie King Village",
    expiresAt: "2026-09-13T23:25:00-04:00",
    createdAt: "2026-09-13T00:55:00-04:00",
    photoUrl: "/photos/keyboard-mouse.webp",
  }),
  listing({
    id: "l-printer",
    sellerId: "u-owen",
    title: "HP inkjet printer with scanner",
    description: "Prints over wifi. Half a cartridge left in each colour. Rent it for the term instead of paying for library printing.",
    kind: "Printer",
    category: "electronics",
    offerType: "rent",
    priceCents: 1500,
    condition: "good",
    pickupArea: "King St N",
    expiresAt: null,
    createdAt: "2026-09-10T20:05:00-04:00",
    photoUrl: "/photos/printer.webp",
  }),
  listing({
    id: "l-projector",
    sellerId: "u-jordan",
    title: "Mini projector with HDMI",
    description: "Point it at a white wall for movie nights. Works with a laptop or a Chromecast. Borrow it for the weekend.",
    kind: "Projector",
    category: "electronics",
    offerType: "lend",
    priceCents: null,
    condition: "good",
    pickupArea: "Columbia St W",
    expiresAt: null,
    createdAt: "2026-09-10T05:05:00-04:00",
    photoUrl: "/photos/projector.webp",
  }),

  // Hygiene
  listing({
    id: "l-shower-caddy",
    sellerId: "u-aisha",
    title: "Shower caddy and bath mat",
    description: "Mesh caddy for the walk to the residence showers, plus a bath mat that’s been through the wash.",
    kind: "Caddy",
    category: "hygiene",
    offerType: "sale",
    priceCents: 600,
    condition: "good",
    pickupArea: "Village 1",
    expiresAt: "2026-09-13T23:30:00-04:00",
    createdAt: "2026-09-13T05:15:00-04:00",
    photoUrl: "/photos/shower-caddy.webp",
  }),
  listing({
    id: "l-toiletries",
    sellerId: "u-priya",
    title: "Unopened toiletries",
    description: "Shampoo, conditioner, body wash and two tubes of toothpaste, all still sealed. Can’t take liquids on the move.",
    kind: "Toiletries",
    category: "hygiene",
    offerType: "free",
    priceCents: null,
    condition: "new",
    pickupArea: "St. Jerome's",
    expiresAt: "2026-09-13T23:35:00-04:00",
    createdAt: "2026-09-12T19:20:00-04:00",
    photoUrl: "/photos/toiletries.webp",
  }),
  listing({
    id: "l-hair-clippers",
    sellerId: "u-owen",
    title: "Hair clippers with all the guards",
    description: "Wahl clippers, blades cleaned and disinfected after every use. Borrow them instead of paying for a haircut.",
    kind: "Clippers",
    category: "hygiene",
    offerType: "lend",
    priceCents: null,
    condition: "good",
    pickupArea: "King St N",
    expiresAt: null,
    createdAt: "2026-09-11T18:05:00-04:00",
    photoUrl: "/photos/hair-clippers.webp",
  }),

  // Other
  listing({
    id: "l-suitcase",
    sellerId: "u-jordan",
    title: "Large suitcase with spinner wheels",
    description: "28 inch, fits a month of clothes. Borrow it for a trip home and bring it back when you’re done.",
    kind: "Suitcase",
    category: "other",
    offerType: "lend",
    priceCents: null,
    condition: "good",
    pickupArea: "Columbia St W",
    expiresAt: null,
    createdAt: "2026-09-10T18:05:00-04:00",
    photoUrl: "/photos/suitcase.webp",
  }),
  listing({
    id: "l-bike",
    sellerId: "u-jordan",
    title: "Hybrid bike with a U-lock",
    description: "Medium frame, 21 speeds, new brake pads. Rent it for the term. The lock and both keys come with it.",
    kind: "Bike",
    category: "other",
    offerType: "rent",
    priceCents: 4000,
    condition: "good",
    pickupArea: "Columbia St W",
    expiresAt: null,
    createdAt: "2026-09-12T17:35:00-04:00",
    photoUrl: "/photos/bike.webp",
  }),
  listing({
    id: "l-tent",
    sellerId: "u-owen",
    title: "Two-person tent",
    description: "Sets up in ten minutes, rain fly included. Rent it for the term for reading week camping.",
    kind: "Tent",
    category: "other",
    offerType: "rent",
    priceCents: 1500,
    condition: "good",
    pickupArea: "King St N",
    expiresAt: null,
    createdAt: "2026-09-10T00:05:00-04:00",
    photoUrl: "/photos/tent.webp",
  }),
  listing({
    id: "l-tower-fan",
    sellerId: "u-owen",
    title: "Oscillating tower fan",
    description: "Residence rooms stay hot until October. Rent it for the term, quiet on the lowest setting.",
    kind: "Fan",
    category: "other",
    offerType: "rent",
    priceCents: 1000,
    condition: "like-new",
    pickupArea: "King St N",
    expiresAt: null,
    createdAt: "2026-09-12T22:05:00-04:00",
    photoUrl: "/photos/tower-fan.webp",
  }),
  listing({
    id: "l-yoga-mat",
    sellerId: "u-hana",
    title: "Yoga mat and resistance bands",
    description: "Thick purple mat and a set of three bands. Wiped down and rolled up, ready to go.",
    kind: "Mat",
    category: "other",
    offerType: "free",
    priceCents: null,
    condition: "good",
    pickupArea: "Mackenzie King Village",
    expiresAt: "2026-09-17T21:05:00-04:00",
    createdAt: "2026-09-13T01:05:00-04:00",
    photoUrl: "/photos/yoga-mat.webp",
  }),
];

const lester = "318 St. Jerome's, unit 4";

function slot(id: string, listingId: string, start: string, end: string, place: string, placeKind: TimeSlot["placeKind"]): TimeSlot {
  return { id, listingId, startsAt: `${start}:00-04:00`, endsAt: `${end}:00-04:00`, place, placeKind };
}

export const slots: TimeSlot[] = [
  slot("s-room-1", "l-priya-room", "2026-09-15T03:05", "2026-09-15T04:05", lester, "seller"),
  slot("s-room-2", "l-priya-room", "2026-09-15T19:05", "2026-09-15T20:05", lester, "seller"),
  slot("s-room-3", "l-priya-room", "2026-09-15T20:05", "2026-09-15T21:05", lester, "seller"),

  slot("s-mattress-1", "l-mattress", "2026-09-13T21:05", "2026-09-13T22:35", "Village 1", "seller"),

  slot("s-coat-1", "l-lab-coat", "2026-09-14T01:05", "2026-09-14T01:35", "E7 atrium", "campus"),
  slot("s-coat-2", "l-lab-coat", "2026-09-14T02:35", "2026-09-14T03:05", "Village 1 front desk", "seller"),

  slot("s-lamp-1", "l-floor-lamp", "2026-09-13T22:05", "2026-09-13T23:05", "Village 1", "seller"),
  slot("s-lamp-2", "l-floor-lamp", "2026-09-14T03:05", "2026-09-14T05:05", "Village 1", "seller"),

  slot("s-shelf-1", "l-bookshelf", "2026-09-14T00:05", "2026-09-14T02:05", "Village 1", "seller"),
  slot("s-shelf-2", "l-bookshelf", "2026-09-14T17:05", "2026-09-14T18:05", "Village 1", "seller"),

  slot("s-calc-1", "l-calculator", "2026-09-14T21:05", "2026-09-14T21:35", "SLC main lobby", "campus"),
  slot("s-calc-2", "l-calculator", "2026-09-15T00:35", "2026-09-15T01:05", "Dana Porter Library entrance", "campus"),

  slot("s-poang-1", "l-poang", "2026-09-16T03:05", "2026-09-16T04:05", "Mackenzie King Village lobby", "seller"),
  slot("s-poang-2", "l-poang", "2026-09-16T17:05", "2026-09-16T18:35", "Mackenzie King Village lobby", "seller"),

  slot("s-bio-1", "l-biology", "2026-09-14T22:05", "2026-09-14T22:35", "SLC main lobby", "campus"),
  slot("s-bio-2", "l-biology", "2026-09-15T22:05", "2026-09-15T22:35", "Davis Centre entrance", "campus"),

  slot("s-conv-1", "l-desk-converter", "2026-09-17T02:05", "2026-09-17T03:05", "E7 atrium", "campus"),
  slot("s-conv-2", "l-desk-converter", "2026-09-17T21:05", "2026-09-17T22:05", "E7 atrium", "campus"),

  slot("s-fridge-1", "l-mini-fridge", "2026-09-16T03:05", "2026-09-16T04:05", "King St N", "seller"),
  slot("s-fridge-2", "l-mini-fridge", "2026-09-18T03:05", "2026-09-18T04:05", "SLC main lobby", "campus"),

  slot("s-monitor-1", "l-monitor", "2026-09-15T02:05", "2026-09-15T03:05", "Columbia St W", "seller"),
  slot("s-monitor-2", "l-monitor", "2026-09-17T02:05", "2026-09-17T03:05", "Davis Centre entrance", "campus"),

  slot("s-futon-1", "l-futon", "2026-09-19T22:05", "2026-09-20T00:05", "King St N", "seller"),
  slot("s-futon-2", "l-futon", "2026-09-20T22:05", "2026-09-21T00:05", "King St N", "seller"),

  slot("s-cart-1", "l-rolling-cart", "2026-09-15T02:05", "2026-09-15T04:05", "King St N", "seller"),

  slot("s-chair-1", "l-office-chair", "2026-09-15T04:05", "2026-09-15T05:05", "Columbia St W", "seller"),
  slot("s-chair-2", "l-office-chair", "2026-09-16T01:05", "2026-09-16T01:35", "Davis Centre entrance", "campus"),

  slot("s-kit-1", "l-drafting-kit", "2026-09-14T20:35", "2026-09-14T21:05", "Davis Centre entrance", "campus"),

  slot("s-table-1", "l-kitchen-table", "2026-09-19T19:05", "2026-09-19T21:05", "Columbia St W", "seller"),

  slot("s-board-1", "l-whiteboard", "2026-09-16T00:05", "2026-09-16T00:35", "SLC main lobby", "campus"),

  slot("s-bedside-1", "l-bedside-table", "2026-09-15T02:05", "2026-09-15T02:35", lester, "seller"),

  slot("s-beanbag-1", "l-bean-bag", "2026-09-14T02:05", "2026-09-14T04:05", "Village 1", "seller"),
  slot("s-beanbag-2", "l-bean-bag", "2026-09-14T17:05", "2026-09-14T18:05", "Village 1", "seller"),

  slot("s-table-lend-1", "l-folding-table", "2026-09-16T03:05", "2026-09-16T04:05", "Columbia St W", "seller"),
  slot("s-table-lend-2", "l-folding-table", "2026-09-19T02:05", "2026-09-19T03:05", "Columbia St W", "seller"),

  slot("s-shoe-1", "l-shoe-rack", "2026-09-16T03:05", "2026-09-16T04:05", "Mackenzie King Village lobby", "seller"),
  slot("s-shoe-2", "l-shoe-rack", "2026-09-16T21:05", "2026-09-16T21:35", "E7 atrium", "campus"),

  slot("s-physics-1", "l-physics-textbook", "2026-09-14T21:05", "2026-09-14T21:35", "SLC main lobby", "campus"),
  slot("s-physics-2", "l-physics-textbook", "2026-09-15T19:05", "2026-09-15T20:05", lester, "seller"),

  slot("s-casio-1", "l-exam-calculator", "2026-09-15T01:05", "2026-09-15T01:35", "Davis Centre entrance", "campus"),
  slot("s-casio-2", "l-exam-calculator", "2026-09-16T21:05", "2026-09-16T21:35", "Dana Porter Library entrance", "campus"),

  slot("s-binders-1", "l-binders", "2026-09-15T22:05", "2026-09-15T22:35", "Dana Porter Library entrance", "campus"),
  slot("s-binders-2", "l-binders", "2026-09-17T03:05", "2026-09-17T04:05", "Mackenzie King Village lobby", "seller"),

  slot("s-rice-1", "l-rice-cooker", "2026-09-14T03:05", "2026-09-14T04:05", "Village 1", "seller"),
  slot("s-rice-2", "l-rice-cooker", "2026-09-14T17:35", "2026-09-14T18:20", "Village 1", "seller"),

  slot("s-ipot-1", "l-instant-pot", "2026-09-15T03:05", "2026-09-15T04:05", "King St N", "seller"),
  slot("s-ipot-2", "l-instant-pot", "2026-09-17T21:05", "2026-09-17T21:35", "SLC main lobby", "campus"),

  slot("s-pots-1", "l-pots-pans", "2026-09-14T04:05", "2026-09-14T05:05", "Village 1 front desk", "seller"),
  slot("s-pots-2", "l-pots-pans", "2026-09-15T00:05", "2026-09-15T01:05", "Village 1 front desk", "seller"),

  slot("s-keyboard-1", "l-keyboard-mouse", "2026-09-15T21:05", "2026-09-15T21:35", "E7 atrium", "campus"),
  slot("s-keyboard-2", "l-keyboard-mouse", "2026-09-17T03:05", "2026-09-17T04:05", "Mackenzie King Village lobby", "seller"),

  slot("s-printer-1", "l-printer", "2026-09-15T02:05", "2026-09-15T03:05", "King St N", "seller"),
  slot("s-printer-2", "l-printer", "2026-09-17T02:05", "2026-09-17T03:05", "King St N", "seller"),

  slot("s-projector-1", "l-projector", "2026-09-18T02:05", "2026-09-18T03:05", "Columbia St W", "seller"),
  slot("s-projector-2", "l-projector", "2026-09-18T21:05", "2026-09-18T21:35", "Davis Centre entrance", "campus"),

  slot("s-caddy-1", "l-shower-caddy", "2026-09-14T04:05", "2026-09-14T05:05", "Village 1 front desk", "seller"),
  slot("s-caddy-2", "l-shower-caddy", "2026-09-15T00:05", "2026-09-15T01:05", "Village 1 front desk", "seller"),

  slot("s-toiletries-1", "l-toiletries", "2026-09-15T03:05", "2026-09-15T04:05", lester, "seller"),
  slot("s-toiletries-2", "l-toiletries", "2026-09-15T19:05", "2026-09-15T20:05", lester, "seller"),

  slot("s-clippers-1", "l-hair-clippers", "2026-09-16T04:05", "2026-09-16T05:05", "King St N", "seller"),
  slot("s-clippers-2", "l-hair-clippers", "2026-09-19T20:05", "2026-09-19T21:05", "King St N", "seller"),

  slot("s-suitcase-1", "l-suitcase", "2026-09-17T04:05", "2026-09-17T05:05", "Columbia St W", "seller"),
  slot("s-suitcase-2", "l-suitcase", "2026-09-19T19:05", "2026-09-19T20:05", "Columbia St W", "seller"),

  slot("s-bike-1", "l-bike", "2026-09-15T02:35", "2026-09-15T03:35", "Columbia St W", "seller"),
  slot("s-bike-2", "l-bike", "2026-09-16T01:05", "2026-09-16T01:35", "Davis Centre entrance", "campus"),

  slot("s-tent-1", "l-tent", "2026-09-18T03:05", "2026-09-18T04:05", "King St N", "seller"),
  slot("s-tent-2", "l-tent", "2026-09-20T22:05", "2026-09-20T23:05", "King St N", "seller"),

  slot("s-fan-1", "l-tower-fan", "2026-09-15T03:35", "2026-09-15T04:35", "King St N", "seller"),
  slot("s-fan-2", "l-tower-fan", "2026-09-15T21:05", "2026-09-15T21:35", "SLC main lobby", "campus"),

  slot("s-yoga-1", "l-yoga-mat", "2026-09-16T03:05", "2026-09-16T04:05", "Mackenzie King Village lobby", "seller"),
  slot("s-yoga-2", "l-yoga-mat", "2026-09-16T21:05", "2026-09-16T21:35", "E7 atrium", "campus"),
];

const marcusArrives = "2026-09-15T18:05:00-04:00";
const sofiaArrives = "2026-09-14T23:05:00-04:00";

// When a thing is actually needed, which is not the same as when someone
// lands. Marcus wants his room usable by the weekend; Sofia's first chem lab
// is Wednesday morning and her math tutorial is Thursday.
const marcusSettled = "2026-09-19T05:05:00-04:00";
const sofiaFirstLab = "2026-09-16T17:35:00-04:00";
const sofiaTutorial = "2026-09-17T22:05:00-04:00";
const classesStart = "2026-09-21T17:35:00-04:00";

type WantSeed = Omit<Want, "fulfilled"> & { fulfilled?: boolean };

export const wants: Want[] = (
  [
    { id: "w-marcus-desk", userId: "u-marcus", text: "Desk big enough for a laptop and a monitor", maxPriceCents: 8000, neededBy: marcusSettled },
    { id: "w-marcus-chair", userId: "u-marcus", text: "Comfy chair for studying", maxPriceCents: 5000, neededBy: marcusSettled },
    { id: "w-marcus-lamp", userId: "u-marcus", text: "Lamp", maxPriceCents: null, neededBy: marcusSettled },
    { id: "w-marcus-fridge", userId: "u-marcus", text: "Small fridge for my room", maxPriceCents: 6000, neededBy: marcusSettled },
    { id: "w-marcus-monitor", userId: "u-marcus", text: "Second monitor", maxPriceCents: 2500, neededBy: classesStart },
    { id: "w-marcus-board", userId: "u-marcus", text: "Whiteboard for problem sets", maxPriceCents: 3000, neededBy: classesStart, fulfilled: true },
    { id: "w-sofia-calc", userId: "u-sofia", text: "Graphing calculator for first-year math", maxPriceCents: 7000, neededBy: sofiaTutorial },
    { id: "w-sofia-coat", userId: "u-sofia", text: "Lab coat for chem labs", maxPriceCents: 2000, neededBy: sofiaFirstLab },
    { id: "w-sofia-bio", userId: "u-sofia", text: "Biology textbook", maxPriceCents: 5000, neededBy: classesStart },
    { id: "w-jordan-shelf", userId: "u-jordan", text: "Bookshelf for my textbooks", maxPriceCents: null, neededBy: classesStart },
    { id: "w-owen-shelf", userId: "u-owen", text: "Shelving for studio supplies", maxPriceCents: 3000, neededBy: classesStart },
  ] satisfies WantSeed[]
).map((w) => ({ fulfilled: false, ...w }));

export const matches: Match[] = [
  {
    id: "m-marcus-room",
    userId: "u-marcus",
    listingId: "l-priya-room",
    wantIds: ["w-marcus-desk", "w-marcus-chair", "w-marcus-lamp", "w-marcus-fridge"],
    score: 0.93,
    reason: "Has a desk, a desk chair, a lamp and a mini fridge. Four things off your list in one pickup.",
  },
  {
    id: "m-marcus-fridge",
    userId: "u-marcus",
    listingId: "l-mini-fridge",
    wantIds: ["w-marcus-fridge"],
    score: 0.81,
    reason: "A 1.7 cu ft mini fridge you can rent for the term.",
  },
  {
    id: "m-marcus-converter",
    userId: "u-marcus",
    listingId: "l-desk-converter",
    wantIds: ["w-marcus-desk"],
    score: 0.64,
    reason: "A standing desk converter, not a full desk. Works if your room already has a table.",
  },
  {
    id: "m-marcus-poang",
    userId: "u-marcus",
    listingId: "l-poang",
    wantIds: ["w-marcus-chair"],
    score: 0.58,
    reason: "An armchair rather than a desk chair. Good for reading, not for long study sessions.",
  },
  {
    id: "m-marcus-lamp-free",
    userId: "u-marcus",
    listingId: "l-floor-lamp",
    wantIds: ["w-marcus-lamp"],
    score: 0.88,
    reason: "A tall floor lamp with the bulb still in it, free.",
  },
  {
    id: "m-marcus-lamp-priya",
    userId: "u-marcus",
    listingId: "l-priya-lamp",
    wantIds: ["w-marcus-lamp"],
    score: 0.72,
    reason: "A desk lamp with a USB port, out of Priya's room.",
  },
  {
    id: "m-marcus-monitor",
    userId: "u-marcus",
    listingId: "l-monitor",
    wantIds: ["w-marcus-monitor"],
    score: 0.86,
    reason: "A 27 inch Dell, rented by the term.",
  },
  {
    id: "m-jordan-shelf",
    userId: "u-jordan",
    listingId: "l-bookshelf",
    wantIds: ["w-jordan-shelf"],
    score: 0.9,
    reason: "A 5-shelf bookcase, free, two streets from you.",
  },
  {
    id: "m-owen-shelf",
    userId: "u-owen",
    listingId: "l-bookshelf",
    wantIds: ["w-owen-shelf"],
    score: 0.84,
    reason: "A 5-shelf bookcase, free. Taller than the studio needs but it holds everything.",
  },
  {
    id: "m-owen-shelf-priya",
    userId: "u-owen",
    listingId: "l-priya-shelf",
    wantIds: ["w-owen-shelf"],
    score: 0.7,
    reason: "A 3-shelf bookcase out of Priya's room, $20.",
  },
  {
    id: "m-sofia-calc",
    userId: "u-sofia",
    listingId: "l-calculator",
    wantIds: ["w-sofia-calc"],
    score: 0.95,
    reason: "A TI-84 Plus CE, the graphing calculator first-year math courses allow.",
  },
  {
    id: "m-sofia-coat",
    userId: "u-sofia",
    listingId: "l-lab-coat",
    wantIds: ["w-sofia-coat"],
    score: 0.9,
    reason: "A size M lab coat with goggles, used for CHEM 120.",
  },
  {
    id: "m-sofia-bio",
    userId: "u-sofia",
    listingId: "l-biology",
    wantIds: ["w-sofia-bio"],
    score: 0.87,
    reason: "Campbell Biology, 12th edition. It’s the BIOL 130 textbook.",
  },
];

export const handoffs: Handoff[] = [
  {
    id: "h-whiteboard",
    listingId: "l-whiteboard",
    slotId: "s-board-1",
    buyerId: "u-marcus",
    sellerId: "u-jordan",
    createdAt: "2026-09-13T05:10:00-04:00",
  },
  {
    id: "h-bedside",
    listingId: "l-bedside-table",
    slotId: "s-bedside-1",
    buyerId: "u-sofia",
    sellerId: "u-priya",
    createdAt: "2026-09-13T18:25:00-04:00",
  },
];

export const notifications: UserNotification[] = [
  {
    id: "n-marcus-room",
    userId: "u-marcus",
    kind: "match",
    text: "Priya Raman’s room covers four things on your list: desk, chair, lamp and fridge. Gone by Tue Sep 15, 12pm.",
    href: "/listings/l-priya-room",
    createdAt: "2026-09-13T17:52:00-04:00",
    read: false,
  },
  {
    id: "n-marcus-fridge",
    userId: "u-marcus",
    kind: "match",
    text: "A mini fridge for rent matches “Small fridge for my room”. $25 for the term.",
    href: "/listings/l-mini-fridge",
    createdAt: "2026-09-13T18:07:00-04:00",
    read: false,
  },
  {
    id: "n-marcus-board",
    userId: "u-marcus",
    kind: "handoff",
    text: "Whiteboard from Jordan Kim. Meet at the SLC main lobby, Tue Sep 15 at 3pm.",
    href: "/handoffs/h-whiteboard",
    createdAt: "2026-09-13T05:10:00-04:00",
    read: true,
  },
  {
    id: "n-priya-bedside",
    userId: "u-priya",
    kind: "claim",
    text: "Claimed by Sofia Martins: bedside table. She’s picking it up at your place tomorrow at 5pm.",
    href: "/handoffs/h-bedside",
    createdAt: "2026-09-13T18:25:00-04:00",
    read: false,
  },
  {
    id: "n-priya-room",
    userId: "u-priya",
    kind: "match",
    text: "Your room matched an incoming student’s list. Gone by Tue Sep 15, 12pm unless someone claims it.",
    href: "/listings/l-priya-room",
    createdAt: "2026-09-13T17:52:00-04:00",
    read: true,
  },
  {
    id: "n-sofia-calc",
    userId: "u-sofia",
    kind: "match",
    text: "A TI-84 Plus CE matches “Graphing calculator for first-year math”. Gone by tomorrow at 4pm.",
    href: "/listings/l-calculator",
    createdAt: "2026-09-12T20:05:00-04:00",
    read: false,
  },
  {
    id: "n-sofia-bedside",
    userId: "u-sofia",
    kind: "handoff",
    text: "Bedside table from Priya Raman. Meet at 318 St. Jerome's, unit 4, tomorrow at 5pm.",
    href: "/handoffs/h-bedside",
    createdAt: "2026-09-13T18:25:00-04:00",
    read: true,
  },
  {
    id: "n-jordan-board",
    userId: "u-jordan",
    kind: "claim",
    text: "Claimed by Marcus Chen: whiteboard. Meet at the SLC main lobby, Tue Sep 15 at 3pm.",
    href: "/handoffs/h-whiteboard",
    createdAt: "2026-09-13T05:10:00-04:00",
    read: false,
  },
  {
    id: "n-aisha-coat",
    userId: "u-aisha",
    kind: "reminder",
    text: "Your lab coat is gone by today at 6pm and nobody has claimed it yet.",
    href: "/listings/l-lab-coat",
    createdAt: "2026-09-13T19:05:00-04:00",
    read: false,
  },
];
