import type { Handoff, Listing, Match, TimeSlot, University, User, UserNotification, Want } from "./types";

export const university: University = {
  id: "uw",
  name: "University of Waterloo",
  shortName: "Waterloo",
  emailDomain: "uwaterloo.ca",
};

export const users: User[] = [
  {
    id: "u-marcus",
    name: "Marcus Chen",
    email: "m8chen@uwaterloo.ca",
    universityId: "uw",
    home: "Moving in from Vancouver",
    moveStatus: "arriving",
    moveDate: "2026-09-15T09:00:00-04:00",
    note: "2B Software Engineering",
  },
  {
    id: "u-priya",
    name: "Priya Raman",
    email: "p3raman@uwaterloo.ca",
    universityId: "uw",
    home: "318 Lester St",
    moveStatus: "leaving",
    moveDate: "2026-09-15T14:00:00-04:00",
    note: "Co-op term in Toronto",
  },
  {
    id: "u-sofia",
    name: "Sofia Martins",
    email: "s7martins@uwaterloo.ca",
    universityId: "uw",
    home: "Moving in from Mississauga",
    moveStatus: "arriving",
    moveDate: "2026-09-14T14:00:00-04:00",
    note: "1A Biomedical Engineering",
  },
  {
    id: "u-aisha",
    name: "Aisha Bello",
    email: "a2bello@uwaterloo.ca",
    universityId: "uw",
    home: "Village 1",
    moveStatus: "leaving",
    moveDate: "2026-09-14T20:00:00-04:00",
    note: "Co-op term in Ottawa",
  },
  {
    id: "u-daniel",
    name: "Daniel Osei",
    email: "d4osei@uwaterloo.ca",
    universityId: "uw",
    home: "Sunview St",
    moveStatus: "leaving",
    moveDate: "2026-09-14T10:00:00-04:00",
    note: "Co-op term in Calgary",
  },
  {
    id: "u-hana",
    name: "Hana Yoshida",
    email: "h6yoshida@uwaterloo.ca",
    universityId: "uw",
    home: "Mackenzie King Village",
    moveStatus: "leaving",
    moveDate: "2026-09-17T20:00:00-04:00",
    note: "Co-op term in San Francisco",
  },
  {
    id: "u-jordan",
    name: "Jordan Kim",
    email: "j5kim@uwaterloo.ca",
    universityId: "uw",
    home: "Columbia St W",
    moveStatus: "staying",
    moveDate: null,
    note: "4A Mechatronics",
  },
  {
    id: "u-owen",
    name: "Owen Brooks",
    email: "o9brooks@uwaterloo.ca",
    universityId: "uw",
    home: "King St N",
    moveStatus: "staying",
    moveDate: null,
    note: "3A Architecture",
  },
];

type ListingSeed = Omit<Listing, "universityId" | "isBundle" | "parentId" | "status" | "createdAt" | "description"> &
  Partial<Pick<Listing, "isBundle" | "parentId" | "status" | "createdAt" | "description">>;

function listing(seed: ListingSeed): Listing {
  return {
    universityId: "uw",
    description: "",
    isBundle: false,
    parentId: null,
    status: "available",
    createdAt: "2026-09-10T12:00:00-04:00",
    ...seed,
  };
}

const inPriyasRoom = {
  sellerId: "u-priya",
  category: "furniture",
  offerType: "sale",
  pickupArea: "Lester St",
  expiresAt: "2026-09-15T12:00:00-04:00",
  parentId: "l-priya-room",
} as const;

export const listings: Listing[] = [
  listing({
    id: "l-mattress",
    sellerId: "u-daniel",
    title: "Twin mattress and bed frame",
    description:
      "Frame comes apart with an Allen key, which I’ll leave taped to it. Mattress has a protector on it the whole time. Free, it just can’t come to Calgary.",
    kind: "Bed",
    category: "furniture",
    offerType: "free",
    priceCents: null,
    condition: "good",
    pickupArea: "Sunview St",
    expiresAt: "2026-09-13T13:30:00-04:00",
    createdAt: "2026-09-12T21:30:00-04:00",
  }),
  listing({
    id: "l-lab-coat",
    sellerId: "u-aisha",
    title: "Lab coat and safety goggles",
    description:
      "Size M lab coat from CHEM 120 labs, washed and folded. The goggles have no scratches. I leave for Ottawa tomorrow, so these need to go tonight.",
    kind: "Coat",
    category: "school",
    offerType: "sale",
    priceCents: 1500,
    condition: "good",
    pickupArea: "Village 1",
    expiresAt: "2026-09-13T18:00:00-04:00",
    createdAt: "2026-09-12T09:30:00-04:00",
  }),
  listing({
    id: "l-floor-lamp",
    sellerId: "u-daniel",
    title: "Tall floor lamp",
    description: "IKEA floor lamp, bulb included. It’ll be on the porch. Just take it before I lock up.",
    kind: "Lamp",
    category: "furniture",
    offerType: "free",
    priceCents: null,
    condition: "good",
    pickupArea: "Sunview St",
    expiresAt: "2026-09-13T20:00:00-04:00",
    createdAt: "2026-09-12T18:00:00-04:00",
  }),
  listing({
    id: "l-bookshelf",
    sellerId: "u-daniel",
    title: "5-shelf bookcase",
    description:
      "A little wobbly but it holds a full shelf of textbooks without complaint. I can help carry it down the stairs.",
    kind: "Shelf",
    category: "furniture",
    offerType: "free",
    priceCents: null,
    condition: "fair",
    pickupArea: "Sunview St",
    expiresAt: "2026-09-14T09:00:00-04:00",
    createdAt: "2026-09-11T20:15:00-04:00",
  }),
  listing({
    id: "l-calculator",
    sellerId: "u-aisha",
    title: "TI-84 Plus CE graphing calculator",
    description:
      "Bought it for MATH 137 and barely used it after midterms. Comes with the charging cable and the slide case.",
    kind: "TI-84",
    category: "school",
    offerType: "sale",
    priceCents: 6000,
    condition: "like-new",
    pickupArea: "Village 1",
    expiresAt: "2026-09-14T16:00:00-04:00",
    createdAt: "2026-09-11T10:00:00-04:00",
  }),
  listing({
    id: "l-priya-room",
    sellerId: "u-priya",
    title: "Everything from my room on Lester",
    description:
      "I’m off to Toronto for co-op, so the whole room setup has to go. Good fit for a Lester or Sunview unit. You get all eight things in one pickup, and I’ll help load the car.",
    kind: "Room",
    category: "furniture",
    offerType: "sale",
    priceCents: 14000,
    condition: "good",
    pickupArea: "Lester St",
    expiresAt: "2026-09-15T12:00:00-04:00",
    isBundle: true,
    createdAt: "2026-09-13T08:45:00-04:00",
  }),
  listing({ ...inPriyasRoom, id: "l-priya-desk", title: "IKEA Micke desk, white", kind: "Desk", priceCents: 4500, condition: "good" }),
  listing({ ...inPriyasRoom, id: "l-priya-chair", title: "Mesh desk chair", kind: "Chair", priceCents: 3000, condition: "good" }),
  listing({ ...inPriyasRoom, id: "l-priya-lamp", title: "Desk lamp with USB port", kind: "Lamp", priceCents: 1500, condition: "like-new" }),
  listing({ ...inPriyasRoom, id: "l-priya-fridge", title: "Danby mini fridge, 3.1 cu ft", kind: "Fridge", priceCents: 6000, condition: "good" }),
  listing({ ...inPriyasRoom, id: "l-priya-shelf", title: "3-shelf bookcase", kind: "Shelf", priceCents: 2000, condition: "good" }),
  listing({ ...inPriyasRoom, id: "l-priya-topper", title: "Twin XL mattress topper", kind: "Bed", priceCents: 1500, condition: "fair" }),
  listing({ ...inPriyasRoom, id: "l-priya-mirror", title: "Full-length mirror", kind: "Mirror", priceCents: 1500, condition: "good" }),
  listing({ ...inPriyasRoom, id: "l-priya-hamper", title: "Laundry hamper", kind: "Hamper", priceCents: 500, condition: "good" }),
  listing({
    id: "l-poang",
    sellerId: "u-hana",
    title: "IKEA Poäng armchair",
    description:
      "Birch frame with a beige cushion. Great reading chair. The cushion cover comes off and goes in the wash.",
    kind: "Chair",
    category: "furniture",
    offerType: "sale",
    priceCents: 3500,
    condition: "good",
    pickupArea: "Mackenzie King Village",
    expiresAt: "2026-09-16T10:00:00-04:00",
    createdAt: "2026-09-12T15:00:00-04:00",
  }),
  listing({
    id: "l-biology",
    sellerId: "u-hana",
    title: "Campbell Biology, 12th edition",
    description: "Some highlighting in the first ten chapters. Used it for BIOL 130.",
    kind: "Book",
    category: "school",
    offerType: "sale",
    priceCents: 4000,
    condition: "good",
    pickupArea: "Mackenzie King Village",
    expiresAt: "2026-09-16T10:00:00-04:00",
    createdAt: "2026-09-12T15:10:00-04:00",
  }),
  listing({
    id: "l-desk-converter",
    sellerId: "u-hana",
    title: "Standing desk converter",
    description: "Sits on top of any desk and raises up to 16 inches. Fits a laptop and one monitor side by side.",
    kind: "Desk",
    category: "furniture",
    offerType: "sale",
    priceCents: 5000,
    condition: "like-new",
    pickupArea: "Mackenzie King Village",
    expiresAt: "2026-09-17T18:00:00-04:00",
    createdAt: "2026-09-12T15:20:00-04:00",
  }),
  listing({
    id: "l-mini-fridge",
    sellerId: "u-owen",
    title: "Mini fridge, 1.7 cu ft",
    description: "Quiet enough for a bedroom. Rent it for the term and bring it back at the end of December.",
    kind: "Fridge",
    category: "furniture",
    offerType: "rent",
    priceCents: 2500,
    condition: "good",
    pickupArea: "King St N",
    expiresAt: null,
    createdAt: "2026-09-13T09:00:00-04:00",
  }),
  listing({
    id: "l-monitor",
    sellerId: "u-jordan",
    title: "Dell 27 inch monitor",
    description:
      "1440p with HDMI and DisplayPort. I have two and only use one, so rent it for the term and bring it back in December.",
    kind: "Screen",
    category: "school",
    offerType: "rent",
    priceCents: 3000,
    condition: "good",
    pickupArea: "Columbia St W",
    expiresAt: null,
    createdAt: "2026-09-12T21:00:00-04:00",
  }),
  listing({
    id: "l-futon",
    sellerId: "u-owen",
    title: "Futon that folds into a bed",
    description: "Still folds flat without a fight. It won’t fit in a sedan, so bring a friend and walk it over.",
    kind: "Futon",
    category: "furniture",
    offerType: "sale",
    priceCents: 8000,
    condition: "fair",
    pickupArea: "King St N",
    expiresAt: null,
    createdAt: "2026-09-12T11:00:00-04:00",
  }),
  listing({
    id: "l-rolling-cart",
    sellerId: "u-owen",
    title: "3-tier rolling cart",
    description: "Good for a desk-side printer or bathroom stuff. Free to whoever wants it.",
    kind: "Cart",
    category: "furniture",
    offerType: "free",
    priceCents: null,
    condition: "good",
    pickupArea: "King St N",
    expiresAt: null,
    createdAt: "2026-09-12T08:00:00-04:00",
  }),
  listing({
    id: "l-office-chair",
    sellerId: "u-jordan",
    title: "Office chair with armrests",
    description: "Adjustable height and armrests. Replaced it with a new one, nothing wrong with it.",
    kind: "Chair",
    category: "furniture",
    offerType: "sale",
    priceCents: 4500,
    condition: "good",
    pickupArea: "Columbia St W",
    expiresAt: null,
    createdAt: "2026-09-11T17:30:00-04:00",
  }),
  listing({
    id: "l-drafting-kit",
    sellerId: "u-owen",
    title: "Drafting kit for ARCH 172",
    description: "Scale ruler, set squares, compass and lead holder. Only the eraser is used up.",
    kind: "Kit",
    category: "school",
    offerType: "sale",
    priceCents: 1500,
    condition: "like-new",
    pickupArea: "King St N",
    expiresAt: null,
    createdAt: "2026-09-10T16:00:00-04:00",
  }),
  listing({
    id: "l-kitchen-table",
    sellerId: "u-jordan",
    title: "Kitchen table with two chairs",
    description: "Solid wood, some scratches on top. Needs a car or two people to carry.",
    kind: "Table",
    category: "furniture",
    offerType: "sale",
    priceCents: 6000,
    condition: "fair",
    pickupArea: "Columbia St W",
    expiresAt: null,
    createdAt: "2026-09-08T13:00:00-04:00",
  }),
  listing({
    id: "l-whiteboard",
    sellerId: "u-jordan",
    title: "Whiteboard, 36 by 24 inches",
    description: "Magnetic, with three markers and an eraser. Very good for working through problem sets.",
    kind: "Board",
    category: "school",
    offerType: "sale",
    priceCents: 2000,
    condition: "good",
    pickupArea: "Columbia St W",
    expiresAt: null,
    status: "claimed",
    createdAt: "2026-09-09T19:00:00-04:00",
  }),
  listing({
    id: "l-bedside-table",
    sellerId: "u-priya",
    title: "Bedside table with a drawer",
    description: "Small white nightstand.",
    kind: "Table",
    category: "furniture",
    offerType: "sale",
    priceCents: 1000,
    condition: "good",
    pickupArea: "Lester St",
    expiresAt: "2026-09-15T12:00:00-04:00",
    status: "claimed",
    createdAt: "2026-09-11T08:00:00-04:00",
  }),
];

const lester = "318 Lester St, unit 4";

function slot(id: string, listingId: string, start: string, end: string, place: string, placeKind: TimeSlot["placeKind"]): TimeSlot {
  return { id, listingId, startsAt: `${start}:00-04:00`, endsAt: `${end}:00-04:00`, place, placeKind };
}

export const slots: TimeSlot[] = [
  slot("s-room-1", "l-priya-room", "2026-09-14T18:00", "2026-09-14T19:00", lester, "seller"),
  slot("s-room-2", "l-priya-room", "2026-09-15T10:00", "2026-09-15T11:00", lester, "seller"),
  slot("s-room-3", "l-priya-room", "2026-09-15T11:00", "2026-09-15T12:00", lester, "seller"),

  slot("s-mattress-1", "l-mattress", "2026-09-13T12:00", "2026-09-13T13:30", "Sunview St", "seller"),

  slot("s-coat-1", "l-lab-coat", "2026-09-13T16:00", "2026-09-13T16:30", "E7 atrium", "campus"),
  slot("s-coat-2", "l-lab-coat", "2026-09-13T17:30", "2026-09-13T18:00", "Village 1 front desk", "seller"),

  slot("s-lamp-1", "l-floor-lamp", "2026-09-13T13:00", "2026-09-13T14:00", "Sunview St", "seller"),
  slot("s-lamp-2", "l-floor-lamp", "2026-09-13T18:00", "2026-09-13T20:00", "Sunview St", "seller"),

  slot("s-shelf-1", "l-bookshelf", "2026-09-13T15:00", "2026-09-13T17:00", "Sunview St", "seller"),
  slot("s-shelf-2", "l-bookshelf", "2026-09-14T08:00", "2026-09-14T09:00", "Sunview St", "seller"),

  slot("s-calc-1", "l-calculator", "2026-09-14T12:00", "2026-09-14T12:30", "SLC main lobby", "campus"),
  slot("s-calc-2", "l-calculator", "2026-09-14T15:30", "2026-09-14T16:00", "Dana Porter Library entrance", "campus"),

  slot("s-poang-1", "l-poang", "2026-09-15T18:00", "2026-09-15T19:00", "Mackenzie King Village lobby", "seller"),
  slot("s-poang-2", "l-poang", "2026-09-16T08:00", "2026-09-16T09:30", "Mackenzie King Village lobby", "seller"),

  slot("s-bio-1", "l-biology", "2026-09-14T13:00", "2026-09-14T13:30", "SLC main lobby", "campus"),
  slot("s-bio-2", "l-biology", "2026-09-15T13:00", "2026-09-15T13:30", "Davis Centre entrance", "campus"),

  slot("s-conv-1", "l-desk-converter", "2026-09-16T17:00", "2026-09-16T18:00", "E7 atrium", "campus"),
  slot("s-conv-2", "l-desk-converter", "2026-09-17T12:00", "2026-09-17T13:00", "E7 atrium", "campus"),

  slot("s-fridge-1", "l-mini-fridge", "2026-09-15T18:00", "2026-09-15T19:00", "King St N", "seller"),
  slot("s-fridge-2", "l-mini-fridge", "2026-09-17T18:00", "2026-09-17T19:00", "SLC main lobby", "campus"),

  slot("s-monitor-1", "l-monitor", "2026-09-14T17:00", "2026-09-14T18:00", "Columbia St W", "seller"),
  slot("s-monitor-2", "l-monitor", "2026-09-16T17:00", "2026-09-16T18:00", "Davis Centre entrance", "campus"),

  slot("s-futon-1", "l-futon", "2026-09-19T13:00", "2026-09-19T15:00", "King St N", "seller"),
  slot("s-futon-2", "l-futon", "2026-09-20T13:00", "2026-09-20T15:00", "King St N", "seller"),

  slot("s-cart-1", "l-rolling-cart", "2026-09-14T17:00", "2026-09-14T19:00", "King St N", "seller"),

  slot("s-chair-1", "l-office-chair", "2026-09-14T19:00", "2026-09-14T20:00", "Columbia St W", "seller"),
  slot("s-chair-2", "l-office-chair", "2026-09-15T16:00", "2026-09-15T16:30", "Davis Centre entrance", "campus"),

  slot("s-kit-1", "l-drafting-kit", "2026-09-14T11:30", "2026-09-14T12:00", "Davis Centre entrance", "campus"),

  slot("s-table-1", "l-kitchen-table", "2026-09-19T10:00", "2026-09-19T12:00", "Columbia St W", "seller"),

  slot("s-board-1", "l-whiteboard", "2026-09-15T15:00", "2026-09-15T15:30", "SLC main lobby", "campus"),

  slot("s-bedside-1", "l-bedside-table", "2026-09-14T17:00", "2026-09-14T17:30", lester, "seller"),
];

const marcusArrives = "2026-09-15T09:00:00-04:00";
const sofiaArrives = "2026-09-14T14:00:00-04:00";

type WantSeed = Omit<Want, "fulfilled"> & { fulfilled?: boolean };

export const wants: Want[] = (
  [
    { id: "w-marcus-desk", userId: "u-marcus", text: "Desk big enough for a laptop and a monitor", maxPriceCents: 8000, neededBy: marcusArrives },
    { id: "w-marcus-chair", userId: "u-marcus", text: "Comfy chair for studying", maxPriceCents: 5000, neededBy: marcusArrives },
    { id: "w-marcus-lamp", userId: "u-marcus", text: "Lamp", maxPriceCents: null, neededBy: marcusArrives },
    { id: "w-marcus-fridge", userId: "u-marcus", text: "Small fridge for my room", maxPriceCents: 6000, neededBy: marcusArrives },
    { id: "w-marcus-board", userId: "u-marcus", text: "Whiteboard for problem sets", maxPriceCents: 3000, neededBy: marcusArrives, fulfilled: true },
    { id: "w-sofia-calc", userId: "u-sofia", text: "Graphing calculator for first-year math", maxPriceCents: 7000, neededBy: sofiaArrives },
    { id: "w-sofia-coat", userId: "u-sofia", text: "Lab coat for chem labs", maxPriceCents: 2000, neededBy: sofiaArrives },
    { id: "w-sofia-bio", userId: "u-sofia", text: "Biology textbook", maxPriceCents: 5000, neededBy: sofiaArrives },
  ] satisfies WantSeed[]
).map((w) => ({ fulfilled: false, ...w }));

export const matches: Match[] = [
  {
    id: "m-marcus-room",
    userId: "u-marcus",
    listingId: "l-priya-room",
    wantIds: ["w-marcus-desk", "w-marcus-chair", "w-marcus-lamp", "w-marcus-fridge"],
    score: 0.93,
    reason: "Has a desk, a desk chair, a lamp and a mini fridge. Four things off your list in one pickup.",
  },
  {
    id: "m-marcus-fridge",
    userId: "u-marcus",
    listingId: "l-mini-fridge",
    wantIds: ["w-marcus-fridge"],
    score: 0.81,
    reason: "A 1.7 cu ft mini fridge you can rent for the term.",
  },
  {
    id: "m-marcus-converter",
    userId: "u-marcus",
    listingId: "l-desk-converter",
    wantIds: ["w-marcus-desk"],
    score: 0.64,
    reason: "A standing desk converter, not a full desk. Works if your room already has a table.",
  },
  {
    id: "m-marcus-poang",
    userId: "u-marcus",
    listingId: "l-poang",
    wantIds: ["w-marcus-chair"],
    score: 0.58,
    reason: "An armchair rather than a desk chair. Good for reading, not for long study sessions.",
  },
  {
    id: "m-sofia-calc",
    userId: "u-sofia",
    listingId: "l-calculator",
    wantIds: ["w-sofia-calc"],
    score: 0.95,
    reason: "A TI-84 Plus CE, the graphing calculator first-year math courses allow.",
  },
  {
    id: "m-sofia-coat",
    userId: "u-sofia",
    listingId: "l-lab-coat",
    wantIds: ["w-sofia-coat"],
    score: 0.9,
    reason: "A size M lab coat with goggles, used for CHEM 120.",
  },
  {
    id: "m-sofia-bio",
    userId: "u-sofia",
    listingId: "l-biology",
    wantIds: ["w-sofia-bio"],
    score: 0.87,
    reason: "Campbell Biology, 12th edition. It’s the BIOL 130 textbook.",
  },
];

export const handoffs: Handoff[] = [
  {
    id: "h-whiteboard",
    listingId: "l-whiteboard",
    slotId: "s-board-1",
    buyerId: "u-marcus",
    sellerId: "u-jordan",
    createdAt: "2026-09-12T20:05:00-04:00",
  },
  {
    id: "h-bedside",
    listingId: "l-bedside-table",
    slotId: "s-bedside-1",
    buyerId: "u-sofia",
    sellerId: "u-priya",
    createdAt: "2026-09-13T09:20:00-04:00",
  },
];

export const notifications: UserNotification[] = [
  {
    id: "n-marcus-room",
    userId: "u-marcus",
    kind: "match",
    text: "Priya Raman’s room covers four things on your list: desk, chair, lamp and fridge. Gone by Tue Sep 15, 12pm.",
    href: "/listings/l-priya-room",
    createdAt: "2026-09-13T08:47:00-04:00",
    read: false,
  },
  {
    id: "n-marcus-fridge",
    userId: "u-marcus",
    kind: "match",
    text: "A mini fridge for rent matches “Small fridge for my room”. $25 for the term.",
    href: "/listings/l-mini-fridge",
    createdAt: "2026-09-13T09:02:00-04:00",
    read: false,
  },
  {
    id: "n-marcus-board",
    userId: "u-marcus",
    kind: "handoff",
    text: "Whiteboard from Jordan Kim. Meet at the SLC main lobby, Tue Sep 15 at 3pm.",
    href: "/handoffs/h-whiteboard",
    createdAt: "2026-09-12T20:05:00-04:00",
    read: true,
  },
  {
    id: "n-priya-bedside",
    userId: "u-priya",
    kind: "claim",
    text: "Claimed by Sofia Martins: bedside table. She’s picking it up at your place tomorrow at 5pm.",
    href: "/handoffs/h-bedside",
    createdAt: "2026-09-13T09:20:00-04:00",
    read: false,
  },
  {
    id: "n-priya-room",
    userId: "u-priya",
    kind: "match",
    text: "Your room matched an incoming student’s list. Gone by Tue Sep 15, 12pm unless someone claims it.",
    href: "/listings/l-priya-room",
    createdAt: "2026-09-13T08:47:00-04:00",
    read: true,
  },
  {
    id: "n-sofia-calc",
    userId: "u-sofia",
    kind: "match",
    text: "A TI-84 Plus CE matches “Graphing calculator for first-year math”. Gone by tomorrow at 4pm.",
    href: "/listings/l-calculator",
    createdAt: "2026-09-12T11:00:00-04:00",
    read: false,
  },
  {
    id: "n-sofia-bedside",
    userId: "u-sofia",
    kind: "handoff",
    text: "Bedside table from Priya Raman. Meet at 318 Lester St, unit 4, tomorrow at 5pm.",
    href: "/handoffs/h-bedside",
    createdAt: "2026-09-13T09:20:00-04:00",
    read: true,
  },
  {
    id: "n-jordan-board",
    userId: "u-jordan",
    kind: "claim",
    text: "Claimed by Marcus Chen: whiteboard. Meet at the SLC main lobby, Tue Sep 15 at 3pm.",
    href: "/handoffs/h-whiteboard",
    createdAt: "2026-09-12T20:05:00-04:00",
    read: false,
  },
  {
    id: "n-aisha-coat",
    userId: "u-aisha",
    kind: "reminder",
    text: "Your lab coat is gone by today at 6pm and nobody has claimed it yet.",
    href: "/listings/l-lab-coat",
    createdAt: "2026-09-13T10:00:00-04:00",
    read: false,
  },
];
